# Generated by Django 3.2.9 on 2021-12-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_brandoffer_coupon_redeemedcoupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupen_code',
            new_name='coupon_code',
        ),
    ]
