# Generated by Django 3.2.9 on 2021-11-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.IntegerField(choices=[(1, 'Order Confirmed'), (2, 'Shipped'), (1, 'Out for delivery'), (0, 'cancelled')], default=1),
        ),
    ]
