# Generated by Django 3.2.9 on 2021-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211130_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.IntegerField(choices=[(1, 'Order Confirmed'), (2, 'Shipped'), (3, 'Out for delivery'), (4, 'order delivered'), (0, 'cancelled')], default=1),
        ),
    ]
